### PR TITLE
h5py 2.8.0

### PR DESCRIPTION
**Pull request by ngoldbaum**

### CODE REVIEW

**Comment by matthew-brett** [comment]
I think you're on the latest multibuild/master here.  You need something like:

```
git submodule update --init
cd multbuild
git fetch origin
git checkout -t origin/devel
cd ..
git add multibuild
git commit -m "Update to latest multibuild/devel
```

**Comment by ngoldbaum** [comment]
@matthew-brett any idea what to do about the SSL error for the mac python3.4 build?

**Comment by ngoldbaum** [comment]
https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version is relevant

**Comment by matthew-brett** [comment]
Ah - whoops - try removing this line from `.travis.yml`:

```
        - MANYLINUX_URL=https://nipy.bic.berkeley.edu/manylinux
```

**Comment by ngoldbaum** [comment]
Nope, same failures on Mac Python3.4 and Python3.5.

**Comment by matthew-brett** [comment]
Yes, I've just been debugging.   It's the `setup_requires` section in `setup.py` - it's triggering attempts to install via `easy_install`, and it looks like that is broken.

Try adding `pkgconfig six` to the `BUILD_DEPENDS` line of `.travis.yml`, as in:

```
    - BUILD_DEPENDS="numpy==$NP_BUILD_DEP Cython six pkgconfig"
```

**Comment by ngoldbaum** [comment]
Ah, good call! I was debugging a similar issue recently in one of my projects. `setup_requires` leads to totally incomprehensible errors in the most unexpected places 😄 . Perhaps https://github.com/h5py/h5py/pull/938 will fix this going forward.

**Comment by matthew-brett** [comment]
I'm not sure where we are with pyproject.toml yet.  So far I have had to work round projects with pyproject.toml by using `python setup.py bdist_wheel` rather that `pip wheel`, because pyproject.toml sets of installs of never numpy versions, which either clash with the versions I want, or override them, so the project is then built against the wrong version of numpy.   I can look up the various discussions on pypa/pip if it helps.

**Comment by ngoldbaum** [comment]
Cool that fixed it. Thanks @matthew-brett! @tacaswell I guess the wheels will be up at wheels.scipy.org by late tonight sometime.

**Pull request merged**
