### PR TITLE
add python3.7 builds

### PR DESCRIPTION
**Pull request by ngoldbaum**

### CODE REVIEW

**Review by matthew-brett — COMMENTED** [review]
Should be good - let's give it a go.

**Comment by ngoldbaum** [comment]
Hmm, it looks like nothing made it up to wheels.scipy.org.

**Comment by matthew-brett** [comment]
Ah no, sorry, because you've merged to `master`, the builds went up to the pre-release container at https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/

**Comment by ngoldbaum** [comment]
Ah, I didn't realize there was a distinction. I guess I should have directed the PR at `daily`? Should I make another PR?

**Comment by tacaswell** [comment]
@matthew-brett Can you upload this to pypi when it is happy?

**Pull request merged**
