### PR TITLE
Remove left-over tarballs.

### PR DESCRIPTION
**Pull request by andreabedini**
They are now automatically downloaded from the multibuild script.

### CODE REVIEW

**Comment by andreabedini** [comment]
it fails on OSX but I am a bit puzzled by the error

> multibuild/common_utils.sh: line 86: shell_session_update: command not found

`shell_session_update` is not mentioned anywhere in the repo ...

edit: it's a travis issue https://github.com/travis-ci/travis-ci/issues/6307

**Comment by matthew-brett** [comment]
Sorry - this is a bug in the new default xcode image on travis-ci - see : https://github.com/travis-ci/travis-ci/issues/6522

Try updating the `multibuild` submodule to the latest master.

**Comment by andreabedini** [comment]
ops, too late! will try to update multibuild (I was going to do that next).

**Comment by andreabedini** [comment]
Works now.

**Comment by matthew-brett** [comment]
Great - thanks for your patience.

**Comment by andreabedini** [comment]
Thank you for all this machinery @matthew-brett !

**Pull request merged**
